### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by RaixSplitter**

### CODE REVIEW

**Comment by RaixSplitter** [comment]
Pull request is not ready for merge before a verified cloud run of both train and fastapi...

Branch introduces multiplicative more pytests, functionality, evaluation and less repeated code

**Comment by SebastianBitsch** [comment]
Det er fredag aften og vi er bestået @RaixSplitter

**Comment by RaixSplitter** [comment]
> Det er fredag aften og vi er bestået @RaixSplitter

SÅ FUCKING APPROVE DOG

**Review by SebastianBitsch — APPROVED** [review]
Har ikke kigget det igennem tbh fratager mig ansvaret

**Comment by RaixSplitter** [comment]
Hahaha

**Pull request merged**
